### ISSUE TITLE
NPE in onSuccess

### ISSUE THREAD

**Issue by appschris** [PauloLinhares09/RetroPicker#6]
`Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void br.com.packapps.retropicker.callback.CallbackPicker.onSuccess(android.graphics.Bitmap, java.lang.String)' on a null object reference
       at br.com.packapps.retropicker.fragments.RetroPickerFragment.executeActionResult(RetroPickerFragment.java:292)
       at br.com.packapps.retropicker.fragments.RetroPickerFragment.onActivityResult(RetroPickerFragment.java:277)
       at android.app.Activity.dispatchActivityResult(Activity.java:7802)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4929)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4269)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4330)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)`

Any idea about that?

**Comment by santhosh-annam** [comment]
You might have used "compile" in build.gradle file. Replace with "implementation"

This worked for me. It's bit late response, but it works for others who have come here with same issue.
